var setupInfo = { "setupInfo" : [
{ "HOME_0IN" : "C:/QFT_2021.1/QFT_2021.1/QFT/V2021.1/win64" },{ "QHOME" : "C:/QFT_2021.1/QFT_2021.1/QFT/V2021.1/win64" },{ "ZSH" : "" },{ "ZI_RTLD_LIB" : "" }]};
var category = { "category" : [
{ "categoryId" : "0" , "categoryName":"Rtl Design Style" },
{ "categoryId" : "1" , "categoryName":"Simulation" },
{ "categoryId" : "2" , "categoryName":"Synthesis" },
{ "categoryId" : "3" , "categoryName":"Connectivity" },
{ "categoryId" : "4" , "categoryName":"Reset" },
{ "categoryId" : "5" , "categoryName":"Clock" },
{ "categoryId" : "6" , "categoryName":"Testbench" },
{ "categoryId" : "7" , "categoryName":"Nomenclature Style" },
{ "categoryId" : "8" , "categoryName":"Setup Checks" }]};
var severity = { "severity" : [
{ "severityId" : "0" , "severityName":"Error" },
{ "severityId" : "1" , "severityName":"Warning" },
{ "severityId" : "2" , "severityName":"Info" }]};
var statusObj = { "status" : [
{ "statusId" : "0" , "statusName":"uninspected" },
{ "statusId" : "1" , "statusName":"pending" },
{ "statusId" : "2" , "statusName":"waived" },
{ "statusId" : "3" , "statusName":"bug" },
{ "statusId" : "4" , "statusName":"fixed" },
{ "statusId" : "5" , "statusName":"verified" }]} ;
var checks = { "checks":[
{ "checksId":"0", "checksName":"assign_width_overflow","severityId":"0","categoryId":"0"},
{ "checksId":"1", "checksName":"assign_width_underflow","severityId":"0","categoryId":"0"},
{ "checksId":"2", "checksName":"bus_bits_not_read","severityId":"1","categoryId":"0"},
{ "checksId":"3", "checksName":"implicit_wire","severityId":"2","categoryId":"0"},
{ "checksId":"4", "checksName":"multiplication_operator","severityId":"2","categoryId":"0"},
{ "checksId":"5", "checksName":"unconnected_inst_output","severityId":"1","categoryId":"3"},
{ "checksId":"6", "checksName":"reserved_keyword","severityId":"2","categoryId":"7"},
{ "checksId":"7", "checksName":"case_default_missing","severityId":"0","categoryId":"1"},
{ "checksId":"8", "checksName":"latch_inferred","severityId":"1","categoryId":"0"},
{ "checksId":"9", "checksName":"array_index_with_expr","severityId":"0","categoryId":"0"},
{ "checksId":"10", "checksName":"for_stmt_with_complex_logic","severityId":"1","categoryId":"0"},
{ "checksId":"11", "checksName":"assign_with_multi_arith_operations","severityId":"1","categoryId":"0"},
{ "checksId":"12", "checksName":"if_else_nested_large","severityId":"1","categoryId":"0"},
{ "checksId":"13", "checksName":"fsm_without_one_hot_encoding","severityId":"2","categoryId":"0"},
{ "checksId":"14", "checksName":"if_stmt_with_arith_expr","severityId":"1","categoryId":"0"},
{ "checksId":"15", "checksName":"always_signal_assign_large","severityId":"1","categoryId":"0"},
{ "checksId":"16", "checksName":"parameter_name_duplicate","severityId":"2","categoryId":"7"},
{ "checksId":"17", "checksName":"reset_set_non_const_assign","severityId":"0","categoryId":"4"},
{ "checksId":"18", "checksName":"line_char_large","severityId":"2","categoryId":"0"},
{ "checksId":"19", "checksName":"data_type_not_recommended","severityId":"1","categoryId":"1"},
{ "checksId":"20", "checksName":" ","severityId":"3","categoryId":"9"}]};
var schematicStatus = {  
"assign_width_overflow" : "off",
"assign_width_underflow" : "off",
"bus_bits_not_read" : "on",
"implicit_wire" : "off",
"multiplication_operator" : "off",
"unconnected_inst_output" : "on",
"reserved_keyword" : "off",
"case_default_missing" : "off",
"latch_inferred" : "on",
"array_index_with_expr" : "off",
"for_stmt_with_complex_logic" : "off",
"assign_with_multi_arith_operations" : "off",
"if_else_nested_large" : "off",
"fsm_without_one_hot_encoding" : "off",
"if_stmt_with_arith_expr" : "off",
"always_signal_assign_large" : "off",
"parameter_name_duplicate" : "off",
"reset_set_non_const_assign" : "off",
"line_char_large" : "off",
"data_type_not_recommended" : "off"};
var adaptiveModeStatus = {  
"assign_width_overflow" : "off",
"assign_width_underflow" : "off",
"bus_bits_not_read" : "off",
"implicit_wire" : "off",
"multiplication_operator" : "off",
"unconnected_inst_output" : "off",
"reserved_keyword" : "off",
"case_default_missing" : "off",
"latch_inferred" : "on",
"array_index_with_expr" : "off",
"for_stmt_with_complex_logic" : "off",
"assign_with_multi_arith_operations" : "off",
"if_else_nested_large" : "off",
"fsm_without_one_hot_encoding" : "off",
"if_stmt_with_arith_expr" : "off",
"always_signal_assign_large" : "off",
"parameter_name_duplicate" : "on",
"reset_set_non_const_assign" : "off",
"line_char_large" : "off",
"data_type_not_recommended" : "off"};
var checkAliasMap = { };
var argMap = {  
"1":"lhs_expression",
"2":"lhs_width",
"3":"rhs_width",
"4":"module",
"5":"file",
"6":"line",
"7":"bits",
"8":"signal",
"9":"port",
"10":"instance",
"11":"name",
"12":"reason",
"13":"array",
"14":"line1",
"15":"line2",
"16":"expression",
"17":"count",
"18":"limit",
"19":"parameter",
"20":"module1",
"21":"file1",
"22":"module2",
"23":"file2",
"24":"type"};
