function Hd_cic_float = CIC_float(decf)
%CIC Returns a multirate filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 19-Nov-2025 03:56:07

if nargin < 1
    decf    = 2;  % Decimation Factor
end
diffd   = 1;  % Differential Delay
numsecs = 1;  % Number of Sections

Hd_cic_float = dsp.CICDecimator( ...
    'DecimationFactor', decf, ...
    'DifferentialDelay', diffd, ...
    'NumSections', numsecs);

% [EOF]
