function Hd = CIC_FLOAT
%CIC_FLOAT Returns a multirate filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 22-Nov-2025 19:57:41

decf    = 2;  % Decimation Factor
diffd   = 1;  % Differential Delay
numsecs = 1;  % Number of Sections

Hd = dsp.CICDecimator( ...
    'DecimationFactor', decf, ...
    'DifferentialDelay', diffd, ...
    'NumSections', numsecs);

% [EOF]
