function Hd_FIR = FIR_8
%FIR_8 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 17-Nov-2025 18:58:14

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 750000;  % Sampling Frequency

Fpass = 110000;            % Passband Frequency
Fstop = 185000;            % Stopband Frequency
Dpass = 0.011512416822;    % Passband Ripple
Dstop = 0.00056234132519;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd_FIR = dsp.FIRFilter( ...
    'Numerator', b, ...
    'CoefficientsDataType', 'Custom', ...
    'CustomCoefficientsDataType', numerictype(true,16,16));

% [EOF]
