function Hd_FIR_comp = FIR_comp
%FIR_COMP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 22-Nov-2025 10:42:20

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

Fpass = 0.64;              % Passband Frequency
Fstop = 0.74;              % Stopband Frequency
Dpass = 0.023021782436;    % Passband Ripple
Dstop = 0.00031622776602;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop], [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd_FIR_comp = dfilt.dffir(b);

% [EOF]
