function Hd = IIR_2_4_FLOAT
%IIR_1_FLOAT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 22-Nov-2025 19:54:25

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 6000000;  % Sampling Frequency

Fnotch = 2400000;  % Notch Frequency
BW     = 50000;    % Bandwidth
Apass  = 16;       % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
