function Hd_IIR_1_float = IIR_1_float
%IIR_1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and DSP System Toolbox 25.2.
% Generated on: 15-Nov-2025 19:29:50

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 6000000;  % Sampling Frequency

Fnotch = 1000000;  % Notch Frequency
BW     = 50000;    % Bandwidth
Apass  = 16;       % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd_IIR_1_float     = dfilt.df2tsos(b, a);

% Set the arithmetic property.
set(Hd_IIR_1_float, 'Arithmetic', 'double');



% [EOF]
